title: Nishu Kumari Singh
description: Personal portfolio showcasing my academic journey, and applied work in data science and Bayesian machine learning. Built on a foundation in mathematics, this site highlights projects, skills, and achievements that reflect my commitment to rigorous analysis, intelligent systems, and meaningful impact.
theme: jekyll-theme-cayman
